### ISSUE TITLE
Option to have manifest keys be relative to compiler context directory

### ISSUE THREAD

**Issue by QWp6t** [webdeveric/webpack-assets-manifest#10]
## The problem
Given that my context directory is _assets_ and I have the following two files...
* assets/scripts/main.js
* assets/styles/main.css

... I'd like the ability to have the manifest keys be relative paths to those files from the context directory.

Current output:
```json
{
  "main.js": "scripts/main_abcdef.js",
  "main.css": "styles/main_abcdef.css"
}
````

I'd like the ability to make the keys look like this:
```json
{
  "scripts/main.js": "scripts/main_abcdef.js",
  "styles/main.css": "styles/main_abcdef.css"
}
```

I was originally going to submit this as a PR, but honestly I'm not even sure where the best place would be to achieve this. 

### Webpack version
2.1.0-beta.25

### Webpack config
The config is a bit of a beast. It's probably easier to just browse it in our repo:

Full config: [assets/build](https://github.com/roots/sage/tree/alpha4/assets/build)
Your plugin is configured here: [assets/build/webpack.config.js#L180-L192](https://github.com/roots/sage/blob/alpha4/assets/build/webpack.config.js#L180-L192)
Hack I'm using to get my desired output: [assets/build/util/assetManifestFormatter.js](https://github.com/roots/sage/blob/alpha4/assets/build/util/assetManifestsFormatter.js)

(If I delete that branch, I'll be sure to come here and update the links.)

### Operating system
Windows, but our users are on all platforms.

**Comment by webdeveric** [comment]
@QWp6t I recently ran into an issue where two dependencies were including a file with the same name and only one entry was being saved to the manifest. I ended up setting the keys relative to the compiler context, which solved my specific issue.

```js
manifest.on('moduleAsset', function(manifest, key, hashedFile, module) {
  manifest.set( path.relative(manifest.compiler.context, module.userRequest), hashedFile );
});
```

Something similar to this should get you close to what you're looking for.

```js
if (config.enabled.cacheBusting) {
  const WebpackAssetsManifest = require('webpack-assets-manifest');

  const manifest = new WebpackAssetsManifest({
    output: 'assets.json',
    assets: config.manifest,
  });

  manifest.on('moduleAsset', function(manifest, key, hashedFile, module) {
    manifest.delete(key);
    manifest.set( path.relative(manifest.compiler.context, module.userRequest), hashedFile );
  });

  manifest.on('processAssets', function(manifest, assets) {
    // Similar to previous example
  });

  webpackConfig.plugins.push( manifest );
}
```

If that doesn't do it, I'll look into adding a feature to do this.

**Comment by QWp6t** [comment]
Yeah, that was the first approach that I did, but unfortunately the `moduleAssets` event doesn't cover the problematic files since they're entry points. I tried looking at the `processAssets` event, but [the `assets` object](https://github.com/webdeveric/webpack-assets-manifest/blob/master/src/WebpackAssetsManifest.js#L179-L201) contains the `hashedFile` but not the source file, which isn't a reliable way of looking up the file. But since the `assets` object seems to supply the entry point key (since I use entry point object, not array), I could possibly figure out a way to look up the source file based on that key. But would this reliably cover all assets that are problematic like this?

Well at any rate, it sounds like this is on me to figure out since you seem to already provide ways of doing this through the event system. So I'll go ahead an close this issue. Thanks for response. Thanks for the example code; that was generous of you. And thanks for creating and maintaining this plugin.

**Comment by webdeveric** [comment]
@QWp6t I've added a couple options to `v0.7.0` that you may find useful.

- [`customize`](https://github.com/webdeveric/webpack-assets-manifest#customize-callback)
- [`contextRelativeKeys`](https://github.com/webdeveric/webpack-assets-manifest#options)

I went ahead and cloned your project to see what it would take to replicate what you have here: https://github.com/roots/sage/blob/74b485be95aa25a398d1d91f2f99328c422ff043/resources/assets/build/webpack.config.js#L167-L179

The following code does the same as what yours does, but without using your `assetManifestsFormatter`.

```js
if (config.enabled.cacheBusting) {
  const WebpackAssetsManifest = require('webpack-assets-manifest');
  const path = require('path');

  webpackConfig.plugins.push(
    new WebpackAssetsManifest({
      output: 'assets.json',
      assets: config.manifest,
      customize(key, value, originalValue) {
        return {
          key: `${path.dirname(originalValue)}/${key}`,
        };
      },
    })
  );
}
```
