### ISSUE TITLE
File-loader assets aren't received when using Webpack 5 cache

### ISSUE THREAD

**Issue by ivnflpz** [webdeveric/webpack-assets-manifest#100]
## The problem
When using the new Webpack 5 persistent cache, the manifest.json is missing all assets from the file-loader on rebuilds. 

## Technical details
I peeked at the entries the plugin receives by tapping into `customize` hook and I was able to verify that its not receiving any assets from the file-loader on rebuild. If I delete the cache, the assets are in the manifest. This might be related to the deprecation warning on the NormalModule hooks that you're already working on so this may be a no-op.

### Webpack version
5.1.3

### Webpack config
I can't share the whole config but these are the relevant parts:
```
// manifest plugin
const manifest = new WebpackAssetsManifest({
  output: 'manifest.json',
  space: 2,
  writeToDisk: true,
  fileExtRegex: /\.\w{2,4}\.(?:map|gz)$|\.\w+$/i,
  sortManifest: true,
  merge: true,
  publicPath: true,
  entrypoints: true,
  entrypointsKey: 'entrypoints',
});

// file-loader
{
    test: /(.jpg|.jpeg|.png|.gif|.tiff|.ico|.svg|.eot|.otf|.ttf|.woff|.woff2)$/i,
    use: [
      {
         loader: 'file-loader',
         options: {
           name: 'media/[path][name].[ext]',
         },
       },
    ],
},

// persistent cache config
cache: {
    type: "filesystem",
    buildDependencies: {
      config: [__filename],
    },
  },
```
### Operating system
macOS 10.15.6

**Comment by webdeveric** [comment]
@ivnflpz Can you try using the plugin version from my `dev` branch? It has initial support for Webpack 5 and it is a work in progress so do not use in production.

```shell
npm install webdeveric/webpack-assets-manifest#dev
```

**Comment by ivnflpz** [comment]
@webdeveric Yeah, looks like your changes fix this issue. Awesome! Curious if there's an ETA on your changes?

**Comment by webdeveric** [comment]
@ivnflpz I'm going to try and address some other outstanding issues before I release an update. I'll work on it some more this week.
Not sure on when exactly I'll publish an update but it'll let you know when I do.

**Comment by ivnflpz** [comment]
Sounds good. Thanks for the great work!

**Comment by webdeveric** [comment]
@ivnflpz I've published a new version that works with webpack 5.
