### ISSUE TITLE
Plugin doesn't ignore hot updates

### ISSUE THREAD

**Issue by dayAlone** [webdeveric/webpack-assets-manifest#11]
assets.json after hot update compile:
```javascript
{
  "app.js": "1.fc31182789ce6d98ae10.hot-update.js",
  "metadata": {
    "version": "d938fc100e5d21ec141d7bd8623ee2d83e99ddcf"
  }
}
```

**Comment by webdeveric** [comment]
@dayAlone Can you provide a webpack config that demonstrates the issue?

**Comment by dayAlone** [comment]
I can't repeat this behaviour at simplified config, but on my big project this happens, maybe you can add some exception for files that contain ".hot-update" string in their filename?

**Comment by anfinil** [comment]
Have the same problem. I fixed it here: https://github.com/anfinil/webpack-assets-manifest/commit/dd709324fe4cafa1e72746c348a75f963090f1e8. Would be like to PR it but can't find rules of HMR update naming.

**Comment by webdeveric** [comment]
@anfinil I'll take a look at it this weekend.

**Comment by webdeveric** [comment]
@dayAlone / @anfinil Can you explain how you're using the `manifest.json` file? How does having a `.hot-update.js` entry affect you? If having that entry is an issue, what does the desired entry look like to you? Should it be skipped or should the value be something else?

@anfinil I think https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L59 is where the HMR naming is defined.

@dayAlone, In your sample output, where is `metadata.version` coming from? Are you adding that yourself?

**Comment by anfinil** [comment]
@webdeveric I'm using `manifest.json` to load assets that were generated by Webpack to web page manually. I look into `manifest.json` for `app.js` bundle to get correct path to the script. It works fine for the first time (when no `not-update` generated). When `hot-update.js` is generated it replaces path for `app.js`. So when I reload page it will load only `hot-update.js` instead of app bundle.

**Comment by webdeveric** [comment]
@anfinil @dayAlone I've added support for ignoring HMR files. Its currently in my dev branch. Check it out and let me know if that works for you.

**Comment by dayAlone** [comment]
@webdeveric It works for me! 🎉

**Comment by brandoniffert** [comment]
The fix works for me when I am not using the `entrypoints: true` option, but when I do use it, the hot-update is present still after a hot reload.

**manifest.json - Initial WDS start**
```
{
  "app.css": "app.css",
  "app.js": "app.js",
  "entrypoints": {
    "app": {
      "js": [
        "vendor.js",
        "app.js"
      ],
      "css": [
        "app.css"
      ]
    }
  },
  "vendor.js": "vendor.js"
}
```

**manifest.json - After a hot reload**
```
{
  "app.css": "app.css",
  "app.js": "app.js",
  "entrypoints": {
    "app": {
      "js": [
        "vendor.js",
        "app.js",
        "app.7ca503d12690c9c3e73b.hot-update.js"
      ],
      "css": [
        "app.css"
      ]
    }
  },
  "vendor.js": "vendor.js"
}
```

**Comment by webdeveric** [comment]
@brandoniffert Can you install from my dev branch and see if that works for you?

```
npm install https://github.com/webdeveric/webpack-assets-manifest.git#dev
```

**Comment by brandoniffert** [comment]
@webdeveric Yeah, that works. Thanks for the quick response!

**Comment by webdeveric** [comment]
@brandoniffert The updated version has been published to npm.
