### ISSUE TITLE
Saving files in watch mode changes paths in assets file

### ISSUE THREAD

**Issue by Monokai** [webdeveric/webpack-assets-manifest#115]
## The problem

I'm working on a project that runs webpack in watch mode using the `devServer` config. When I start the project, everything works fine and all the paths in the resulting assets manifest are correct. Whenever I change my code and save a random JS file, the assets paths are changed.

Version 3 didn't show this behavior, even with Webpack 5.

## Technical details

paths on first run:

```json
"images/image.svg": "http://localhost:3000/images/image.svg"
```

after a save of a random JS file:

```json
"image.svg": "http://localhost:3000/images/image.svg"
```

You can see that `outputPath` seems to be discarded.

### Webpack version

5.10.0

### Webpack config

…

```js
{
	test   : /\.svg/,
	loader : 'file-loader',
	options: {
		name      : '[name]-[contenthash:16].[ext]',
		outputPath: 'images',
		esModule  : false
	}
}
```

…

```js
new WebpackAssetsManifest({
	output              : 'assets.json',
	space               : 2,
	writeToDisk         : true,
	publicPath          : true,
	entrypoints         : true,
	entrypointsUseAssets: true
})
```

### Operating system

Docker `node:14-alpine`

**Comment by mpg-tomoya-komiyama** [comment]
Same here with `webpack-assets-manifest@~5` and `~4`.
It works fine with `~3`.

**Comment by dkrnl** [comment]
same issue:
```json
  "og-image.png": {
    "src": "/img/og-image.png",
    "integrity": "..."
  },

```

**Comment by Stanzilla** [comment]
Same here

**Comment by webdeveric** [comment]
@Monokai Can you install the plugin from my `watch-mode-update` branch and try again?

```shell
npm install webdeveric/webpack-assets-manifest#watch-mode-update
```

**Comment by mpg-tomoya-komiyama** [comment]
> `watch-mode-update` branch

@webdeveric
It seems to be fine in my project👍

**Comment by Monokai** [comment]
@webdeveric Seems to be working. Thanks!

**Comment by webdeveric** [comment]
@Monokai @mpg-tomoya-komiyama I've published an updated version to npm.
