### ISSUE TITLE
moduleAsset event listener doesn't work?

### ISSUE THREAD

**Issue by nh51515** [webdeveric/webpack-assets-manifest#12]
## The problem
moduleAsset event listener is not triggered
## Technical details
I was trying to log messages on each of the event listeners. But it seems moduleAsset event listener is never called. Is there any reason why? Thank you in advance.
### Webpack version
1.14.0
### Webpack config
```javascript
new WebpackAssetsManifest({
    output: 'manifest.json',
    replacer: null,
    space: 2,
    writeToDisk: true,
    fileExtRegex: /\.\w{2,4}\.(?:map|gz)$|\.\w+$/i,
    sortManifest: true,
    merge: true,
    publicPath: '',
    apply: function(manifest){
      console.log('apply');
    },
    moduleAsset: function(manifest, key, hashedFile, module){
      console.log('moduleAsset');
    },
    processAssets: function(manifest, assets){
      console.log('processAssets');
    },
    done: function(manifest, stats){
      console.log('done');
    }
   }),
```
### Operating system
MacOS

**Comment by webdeveric** [comment]
@nh51515, `moduleAsset` is called when a module requires/imports an asset. Example: https://github.com/webdeveric/webpack-assets-manifest/blob/master/test/fixtures/client.js#L3

Are you requiring any images or CSS from your entry points (JS files)?

**Comment by nh51515** [comment]
@webdeveric In my entry point (js file), it imports another module that contains sass files. There is no explicit require for css in this case. So moduleAsset is not called in this case?

**Comment by webdeveric** [comment]
@nh51515 What other plugins are you using? It would be helpful to see your full webpack config. Do you have a simplified working example that shows the issue you're having? Maybe in a public repo or a gist?

**Comment by nh51515** [comment]
Now I know more about how compiler works, I realized moduleAsset is working properly. I missed the detail that handleModuleAsset is not registered on this.compiler, but registered on the passed-in compilation instance. I will close it.
