### ISSUE TITLE
Manifest is written to multiple places when included in Angular build

### ISSUE THREAD

**Issue by trickeyone** [webdeveric/webpack-assets-manifest#125]
I wanted to move to this plugin instead of a different manifest plugin. However, it appears that the `manifest.json` is written in the compiler's output directory as well as the actual path specified for the manifest to be written. I am passing an absolute path for the output.

When Angular loads up, it does a `require('webpack-dev-server')` to simply include it in it's CLI startup. This results in `process.env.WEBPACK_DEV_SERVER` being set by default, even if the server is not being started. So, when the manifest plugin runs its `emitAssetsManifest` it sets the file path as just the basename (as outlined in #89). This ultimately results in the manifest being written by webpack to the base output directory as well as written to disk via the plugin to the expected output path.

https://github.com/webdeveric/webpack-assets-manifest/blob/ace94e69ba2088f53a0c05ebd2047ac399e04028/src/WebpackAssetsManifest.js#L710

I have been able to override this issue by adding this to my build:
```
if (process.env.WEBPACK_DEV_SERVER) {
  delete process.env.WEBPACK_DEV_SERVER;
}
```

I had to actually delete it because, even setting the value to `false` resulted in a truthy value. Anything set on `process.env` is being converted to a string, so the result is actually `'false'` resolving to `true`

This isn't ideal, but it is resolving the issue, as I don't use webpack-dev-server.

I understand the thinking behind checking for the environment variable being set, but it did cause an issue that took some time to track down the root cause. Maybe if `writeToDisk` is set to `true` or the output path is absolute maybe don't do the dev server check? Just brainstorming.

**Comment by webdeveric** [comment]
@trickeyone Good catch. I hadn't thought of a package including `webpack-dev-server` but not using it.
I'll try and rework it when I get some time.

**Comment by webdeveric** [comment]
@trickeyone I've made some updates. Can you try with my branch?

```shell
npm install webdeveric/webpack-assets-manifest#dev-server
```

**Comment by webdeveric** [comment]
@trickeyone I published new versions that have this update.

**Comment by trickeyone** [comment]
@webdeveric I'm so sorry, I totally forgot to followup on this after I got the notification email back in April. I can confirm that I no longer see the issue. I tested by removing my work-around and the compilation completed as normal. Thanks!!
