### ISSUE TITLE
lost [path] in key when boot with webpack 5 persistent cache

### ISSUE THREAD

**Issue by kikyous** [webdeveric/webpack-assets-manifest#131]
## The problem
my webpack file-loader config
```js
        {
          test: /\.(gif|png|jpe?g)$/i,
          use: [
            {
              loader: "file-loader",
              options: {
                name: "[path][name].[ext]",
                esModule: false,
              },
            },
          ],
        },
```

enable persistent cache:
```
    cache: {
      type: "filesystem",
      buildDependencies: {
        config: [__filename],
      },
    },
```
first boot without persistent cache, it generate the correct manifest file,
```json
{
  "assets/images/large/course-cover-default.jpg": "..."
}
```

restart webpack-dev-server with persistent cache , manifest file become:

```json
{
  "course-cover-default.jpg": "..."
}
```

## Technical details
No

### Webpack version
5.21.1

### Webpack config
    new WebpackAssetsManifest({
      output: "manifest.json",
      writeToDisk: true,
      entrypoints: true,
      publicPath: true,
    }),

### Operating system
macos big sur 11.1

### related
https://github.com/webpack/webpack/issues/12616

**Comment by webdeveric** [comment]
@kikyous I was able to replicate the issue you're having with the `webpack` cache and `file-loader` assets. I'll take a look and see what I can find out as to why that is happening.

I was unable to cause `webpack-dev-server` to fail to start, like you mentioned in your related issue.
By the look of the error message, its related to asset modules, but you didn't mention that in this issue.

 Do you have a minimal reproducible example I can clone and run locally?

**Comment by kikyous** [comment]
In related issue i use webpack 5 asset module instead of file-loader.
and webpack config like this:

```js
  cache: {
      type: "filesystem",
      buildDependencies: {
        config: [__filename],
      },
   },
 output: {
      filename: "[name].js",
      path: path.resolve(__dirname, "static"),
      assetModuleFilename: '[path][name].[ext][query]',
      publicPath: "/static/",
  },
 module: {
   rules: [
     {
       test: /\.(gif|png|jpe?g)$/i,
       type: 'asset/resource'
     }
   ]
 },
plugins: [
  new WebpackAssetsManifest({
    output: "manifest.json",
    writeToDisk: true,
    entrypoints: true,
    publicPath: true,
  }),
]
```

**Comment by kikyous** [comment]
if you cant not replicate the related issue using above config, I will create a minimal reproducible example.

**Comment by gustaff-weldon** [comment]
I believe I have the same problem. It does not matter if I use `cache: true/false`, it fails.
I will try to extract full config.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.dirname (path.js:1128:5)
    at WebpackAssetsManifest.handleProcessAssetsAnalyse (/Users/bernard/work/projectx/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:496:31)
    at fn (/Users/bernard/work/projectx/node_modules/webpack/lib/Compilation.js:371:10)
    at _next1 (eval at create (/Users/redacted/work/projectx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at eval (eval at create (/Users/redacted/work/projectx/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at /Users/redacted/work/projectx/node_modules/webpack/lib/Compilation.js:412:10
    at /Users/redacted/work/projectx/node_modules/webpack/lib/SourceMapDevToolPlugin.js:540:10
    at /Users/redacted/work/projectx/node_modules/neo-async/async.js:2830:7
    at done (/Users/redacted/work/projectx/node_modules/neo-async/async.js:2865:11)
```

**Comment by gustaff-weldon** [comment]
☝️  I have found out that my problem was related to switching to `AssetModule` from `file-loader`.
The signature for name generator function changed from `(fileName: string) => string` to `(pathData: PathData, assetInfo: AssetInfo) => string)`

 previously, we were using custom name function for `file-loader`

**Comment by kikyous** [comment]
@webdeveric any update about this? 😂

**Comment by mildred** [comment]
See webpacker issue above with some details. I have a similar problem (but it happens every time). With the new AssetModule from webpack 5, the path component from the filename is lost in the manifest. I believe this is caused by:

https://github.com/webdeveric/webpack-assets-manifest/blob/43e94b7e595e93853bf3b2a683593882fabbfb57/src/WebpackAssetsManifest.js#L533-L536

where the filename is stripped to its basename before inclusion in the manifest. It makes sense because there is a path prefix to skip, but if the asset in in a subdirectory, then it strips it too. I believe an option can be added to tell which path prefix to skip and which to keep.

**Comment by renchap** [comment]
I am having the same issue after configuring Webpack 5 persistent caching.

I am loading fonts using the `asset/ressource` type:
```js
  {
    test: [
      /\.woff$/,
      /\.woff2$/,
    ],
    type: "asset/resource",
    generator: {
      filename: "static/[name]-[contenthash][ext]",
    },
  },
```

In a CSS file (I am using `css-loader`), I am referencing a font file:

```css
@font-face {
  src: url("~fonts/Montserrat-Regular.woff2") format("woff2");
}
```

Then, in my manifest file, depending on the state of Webpack's persistent cache, the key for this file is either `Montserrat-Regular.woff2` (cache enabled and not empty) or `static/Montserrat-Regular.woff2` (no cache, or empty cache, expected result).

**Comment by webdeveric** [comment]
@kikyous I have an update that should fix your issue. Can you install my branch and give it a try?

```shell
npm install webdeveric/webpack-assets-manifest#persistent-cache-fix
```

**Comment by kikyous** [comment]
@webdeveric this update fix my issue.

**Comment by webdeveric** [comment]
@kikyous I published an updated version with this fix.
