### ISSUE TITLE
Path from glob not correctly used in manifest

### ISSUE THREAD

**Issue by strarsis** [webdeveric/webpack-assets-manifest#132]
## The problem
The from-path of a glob isn't correctly prepended in the manifest.

## Technical details
The files in `images/` are copied into the target directory in their own `images/` subdirectory.
However, the resulting manifest file lists these files without the `images/` subdirectory.
`./assets/images/svg/test.svg` → `./dist/images/svg/test.svg` - That is OK.
`manifest.json`:
```json
"svg/test.svg": "images/svg/test_8d1cd1127fdd86a4657c56ecvnfe16ca.svg",
````
`dist/images/` is missing from the path in the manifest.

### Webpack version
`5.11.1`

### Webpack config
```js
// [...]
    new CopyPlugin({
      patterns: [
        {
          from: 'images/**/*',
          noErrorOnMissing: true,
          to: '[path][name]_[contenthash].[ext]',
        },
      ],
    }),
// [...]
````

### Operating system
WSL 2 (Windows 10 x64)

### Related
https://github.com/webpack-contrib/copy-webpack-plugin/issues/583

**Comment by webdeveric** [comment]
Can you provide a minimal reproducible example I can clone and run locally that shows the issue?

**Comment by strarsis** [comment]
@webdeveric: https://github.com/strarsis/webpack-assets-manifest-path-issue
Clone it, install the npm dependencies, then run the build script: `npm run build`.
The `manifest.json` will contain only the subset of the whole path for files in subfolders, in that example `images/` being missing.

**Comment by strarsis** [comment]
@webdeveric: Can I help further debugging this?

**Comment by strarsis** [comment]
After some debugging I think I found the underlying issue:
The `handleNormalModuleLoader` method monkeypatches the `emitFile` method of the webpack loader context.
This is not sufficient for all keys to be matched later as webpack plugins also emit assets ([`emitAsset`](https://webpack.js.org/api/compilation-object/#emitasset) method), 
which are not handled at all by this plugin, hence will not end in the key lookup later.

**Comment by strarsis** [comment]
Well, after a multi-hour debugging session I found finally found out that the `contextRelativeKeys` option of this plugin fixes the issue. With being turned on, the paths become correct. 😿 
```js
new WebpackAssetsManifest({
  output: 'assets.json',
  space: 2,
  writeToDisk: false,
  assets: config.manifest,
  replacer: require('./util/assetManifestsFormatter'),
  contextRelativeKeys: true,
})
````
