### ISSUE TITLE
Why not use the publicPath setting from the output settings of webpack?

### ISSUE THREAD

**Issue by dietergeerts** [webdeveric/webpack-assets-manifest#14]
Hi,

I was wondering why the plugin doesn't use the publicPath setting of webpack itself? Now you have to set two time the same thing, and it brings confusion, while the publicPath is just for that reason. Maybe I am not thinking of all possible scenarios, but I really can't see why it's needed.

**Comment by webdeveric** [comment]
@dietergeerts You are correct in that they do the same thing, but there is one important difference.

Webpack's `publicPath` should be a `string` (see [documentation](https://webpack.js.org/configuration/output/#output-publicpath)) and the manifest's `publicPath` can be a `string` or a `function`. This allows you to add your own custom logic to determine what gets saved to the manifest. For example: https://github.com/webdeveric/webpack-assets-manifest#add-your-cdn

If you don't need custom logic, you'd be fine just using Webpack's config setting.

**Comment by dietergeerts** [comment]
Thx for the clarification. I'm playing with webpack and haven't worked with it a lot yet, so it can be confusing that different plugins are acting so differently with the webpack settings etc...
