### ISSUE TITLE
entrypoints data is overwritten in multi-compiler mode

### ISSUE THREAD

**Issue by dreyks** [webdeveric/webpack-assets-manifest#140]
## The problem
When using webpack-assets-manifest in a webpack multi-config mode (and passing `assets` to hold the shared state) with `entrypoints: true` the resulting manifest only contains the last config's entrypoints

## Technical details
This here overwrites the whole `this.options.entrypointsKey` with the current compilation entrypoints
https://github.com/webdeveric/webpack-assets-manifest/blob/62b0a73e6a6ef8d39d0680de97de218de13cfaaf/src/WebpackAssetsManifest.js#L589

if I patch this line to be
 ```js
this.setRaw( this.options.entrypointsKey, { ...this.get(this.options.entrypointsKey), ...entrypoints } );
```
everything starts working

### Webpack version
4.46.0 (I'm using webpack-assets-manifest@3.1.1 but judging from the code the issue is present in master too)

### Webpack config
```js
const assets = Object.create(null)

const firstConfig = {
  plugins: [
    new WebpackAssetsManifest({
      entrypoints: true,
      writeToDisk: true,
      assets
    })
  ]
}

const secondConfig = {
  plugins: [
    new WebpackAssetsManifest({
      entrypoints: true,
      writeToDisk: true,
      assets
    })
  ]
}

export default [firstConfig, secondConfig]
```

### Operating system
MacOS 11.2.1

**Comment by webdeveric** [comment]
@dreyks I made lots of updates in v4. Please install that version and see if that fixes your issue.

**Comment by dreyks** [comment]
i'll give it a try

**Comment by webdeveric** [comment]
@dreyks Did v4 solve your issue?

**Comment by dreyks** [comment]
i'm currently unable to switch to v4 since it only supports webpack 5 and i can't yet use it

i'll craft a test repository with webpack 5 and webpack-assets-manifest v4 aand see if it works today

**Comment by webdeveric** [comment]
@dreyks That is not correct. v4 supports webpack 4 only. v5 is the current version of my plugin and it does support webpack 5.

**Comment by dreyks** [comment]
oh, i see. got a bit confused. yup, will upgrade to v4 right away and report back

**Comment by dreyks** [comment]
ok I tried v4.0.1 - same issue: in multicompiler mode and entrypoints set to true the only entrypoints that end up in the final manifest are the ones from the first config

**Comment by dreyks** [comment]
i can reproduce this with a failing test

```js
it('should work with entrypoints', async () => {
  const sharedAssets = Object.create(null)

  const { manifest: manifest1, run: run1 } = create(
    configs.hello(),
    {
      assets: sharedAssets,
      entrypoints: true
    },
  )

  const { manifest: manifest2, run: run2 } = create(
    configs.client(),
    {
      assets: sharedAssets,
      entrypoints: true
    },
  )

  await run1()
  await run2()

  assert.equal(manifest1.toString(), manifest2.toString())
  expect(Object.keys(manifest1.get('entrypoints'))).to.contain('main')
  expect(Object.keys(manifest1.get('entrypoints'))).to.contain('client')
})
```

**Comment by webdeveric** [comment]
@dreyks I have a fix locally. I'll try to publish a new release after I close out a couple more issues.

**Comment by dreyks** [comment]
nice, thx!

**Comment by webdeveric** [comment]
@dreyks Versions `4.0.2` and `5.0.2` have been published.
