### ISSUE TITLE
Unexpected output when using with HMR in development

### ISSUE THREAD

**Issue by MatisLepik** [webdeveric/webpack-assets-manifest#144]
## The problem
I'm using this plugin in development (`devServer: { hot: true }`). Since updating to Webpack 5, this is a bit broken. After making changes to my code, the main entry point in the manifest is replaced with a hot-update.js file, and there's some weird files in the manifest that probably shouldn't be there.

## Technical details
✔️    Manifest after starting the server:
```
{
  "main.js": "main-e91e96b6413ce024dda7.js"
}
```

❌    Manifest after making changes to any file:
```
{
  "main-598c5381f165457d4975.js": "main-598c5381f165457d4975.js",
  "main.e91e96b6413ce024dda7.hot-update.json": "main.e91e96b6413ce024dda7.hot-update.json",
  "main.js": "main.e91e96b6413ce024dda7.hot-update.js"
}
```

The users end up seeing an error like "self.webpackHotUpdate is not a function", since they are being served a partial file instead of the full bundle. 

### Webpack version
webpack: 5.3.0
webpack-assets-manifest: 5.0.2

Note that when downgrading to webpack@4 and webpack-assets-manifest@4, the problem goes away.

### Webpack config
```
const path = require('path');
const WebpackAssetsManifest = require('webpack-assets-manifest');

module.exports = {
  mode: 'development',
  entry: {
    main: './src/index.js'
  },
  output: {
    filename: '[name]-[hash].js',
  },
  plugins: [
    new WebpackAssetsManifest()
  ],
  devServer: {
    hot: true,
    port: 7000,
  },
};
```

### Operating system
macOS Big Sur

Thanks for your time!

**Comment by webdeveric** [comment]
@MatisLepik I've rewritten how HMR assets are filtered. Can you install from my branch and try it out?

```shell
npm install webdeveric/webpack-assets-manifest#dev-hmr
```

**Comment by MatisLepik** [comment]
@webdeveric yes, that seems to fix it! Thanks :)

**Comment by webdeveric** [comment]
@MatisLepik Version `5.0.3` has been published.
