### ISSUE TITLE
Webpack build fails when webpack configuration is in a separate package

### ISSUE THREAD

**Issue by adp-psych** [webdeveric/webpack-assets-manifest#155]
## The problem

webpack-assets-manifest causes a webpack build to fail if the plugin is used in a different package from the package being built. For example, if I create a package, `webpack-config`, that contains a webpack configuration that uses webpack-assets-manifest, and then I try to use `webpack-config` to configure webpack for my main project, the webpack build fails.

## Technical details

Create a directory, `~/webpack-assets-manifest-example`, containing the following files.

`~/webpack-assets-manifest-example/package.json':

```
{
  "name": "temp-webpack",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "webpack": "^5.35.1",
    "webpack-assets-manifest": "^5.0.6",
    "webpack-cli": "^4.6.0"
  }
}
```

`~/webpack-assets-manifest-example/webpack.config.js`:

```
module.exports = require('webpack-config');
```

`~/webpack-assets-manifest-example/src/index.js` (empty):

```
```

`~/webpack-assets-manifest-example/webpack-config/package.json`:

```
{
  "name": "webpack-config",
  "version": "1.0.0",
  "description": "",
  "main": "webpack.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "webpack": "^5.35.1",
    "webpack-assets-manifest": "^5.0.6",
    "webpack-cli": "^4.6.0"
  }
}
```

`~/webpack-assets-manifest-example/webpack-config/webpack.js`:

```
const AssetsManifestPlugin = require('webpack-assets-manifest');

const configuration = (mode) => ({
	'plugins': [
		new AssetsManifestPlugin({
			'entrypoints': true,
			'integrity': true,
			'output': 'assets.json',
			'space': '\t',
		}),
	],
});

module.exports = (environment, argv) => configuration(argv.mode);
```

Now install the packages for the main project and link to `webpack-config` in `node_modules`:

```
(cd ~/webpack-assets-manifest-example && npm install && cd node_modules && ln -sf ../webpack-config)
```

At this point, the main project will build successfully with `(cd ~/webpack-assets-manifest-example && npx webpack)`:

```
asset assets.json 368 bytes [emitted]
asset main.js 0 bytes [emitted] [minimized] (name: main)
./src/index.js 1 bytes [built] [code generated]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value.
Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

webpack 5.35.1 compiled with 1 warning in 224 ms
```

Now install the packages for the `webpack-config` package:

```
(cd ~/webpack-assets-manifest-example/webpack-config && npm install)
```

Now the main project will fail to build with `(cd ~/webpack-assets-manifest-example && npx webpack)`:

```
[webpack-cli] TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (/home/user/webpack-assets-manifest-example/webpack-config/node_modules/webpack/lib/NormalModule.js:181:10)
    at WebpackAssetsManifest.handleCompilation (/home/user/webpack-assets-manifest-example/webpack-config/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:778:18)
    at Hook.eval [as call] (eval at create (/home/user/webpack-assets-manifest-example/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:100:1)
    at Hook.CALL_DELEGATE [as _call] (/home/user/webpack-assets-manifest-example/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/user/webpack-assets-manifest-example/node_modules/webpack/lib/Compiler.js:1017:26)
    at /home/user/webpack-assets-manifest-example/node_modules/webpack/lib/Compiler.js:1059:29
    at Hook.eval [as callAsync] (eval at create (/home/user/webpack-assets-manifest-example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/user/webpack-assets-manifest-example/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/home/user/webpack-assets-manifest-example/node_modules/webpack/lib/Compiler.js:1054:28)
    at /home/user/webpack-assets-manifest-example/node_modules/webpack/lib/Compiler.js:494:12
```

I tried inserting some debugging code in `WebpackAssetsManifest.js` at line 778, at the top of `handleCompilation()`:

```
    console.log(compilation);
    console.log(compilation instanceof Compilation);
```

Adding these lines to the version in `~/webpack-assets-manifest-example/webpack-config/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js` and running `(cd ~/webpack-assets-manifest-example && npx webpack)` outputs a very long object beginning with

```
<ref *2> Compilation {
  hooks: {
    buildModule: Hook {
      _args: [Array],
      name: undefined,
      taps: [],
      interceptors: [],
```

and prints `false` for the `instanceof` test.

Adding these lines to the version in `~/webpack-assets-manifest-example/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js`, removing the packages installed for `webpack-config` with `(cd ~/webpack-assets-manifest-example/webpack-config && rm -rf node_modules)`, and then running `(cd ~/webpack-assets-manifest-example && npx webpack)` again outputs a very long object beginning with

```
<ref *2> Compilation {
  hooks: {
    buildModule: Hook {
      _args: [Array],
      name: undefined,
      taps: [],
      interceptors: [],
```

but prints `true` for the `instanceof` test, and the build succeeds.

This is a problem because it should be possible for the `webpack-config` package to depend directly on webpack-assets-manifest and have its own version installed without breaking the webpack build.

### Webpack version

Output of `npx webpack --version`:

```
webpack 5.35.1
webpack-cli 4.6.0
```

### Webpack config

See above.

### Operating system

Fedora 33

Output of `uname -srvmpio`:

```
Linux 5.4.98-1.fc25.qubes.x86_64 #1 SMP Wed Feb 17 01:49:26 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Output of `node --version`:

```
v16.0.0
```

Output of `npm --version`:

```
7.11.1
```

**Comment by webdeveric** [comment]
@adp-psych I've seen the `TypeError: The 'compilation' argument must be an instance of Compilation` error when using `npm link`. This is a node module resolution issue on your end and not an issue with this plugin.

I think you can get around it by making `webpack` a peer dependency in your config package and then in your project you should make `webpack` and your config package dev dependencies.
