### ISSUE TITLE
Add non-loaded files to manifest (copy?)

### ISSUE THREAD

**Issue by strarsis** [webdeveric/webpack-assets-manifest#160]
@webdeveric:

## The problem
Some assets are loaded during runtime which means that they are not loaded by a webpack loader during build.
The `manifest.json` still has to contain these files (and their hashed names) so the runtime can find these files and load them.

Is there a way to get the non-loaded assets in assets folder into the manifest, too?

**Comment by webdeveric** [comment]
@strarsis This plugin only knows about assets that the webpack compiler emits.
If you want to modify the assets manifest file to include additional data, you can use the `transform` hook.

**Comment by strarsis** [comment]
@webdeveric: Thanks for your quick response!
The files emitted by the `copy-globs-webpack-plugin` don't end up in the manifest - they aren't explicitly loaded.
Does that plugin use a different mechanism or does it or this plugin need extra configuration?

**Comment by webdeveric** [comment]
@strarsis The github repo for `copy-globs-webpack-plugin` is 404 (maybe private?) so I'm not sure what its doing.
I looked on npm and that package has not been updated in 3 years. Can you try a [`copy-webpack-plugin`](https://webpack.js.org/plugins/copy-webpack-plugin/) instead?

**Comment by strarsis** [comment]
@webdeveric: I just noticed that indeed this is the cause of the issue. Thanks.

**Comment by kimyu92** [comment]
@webdeveric @strarsis I'm still seeing missing files in `manifest.json` without using any hook?

Is it still true that we need to rely on `transform` hook when copying assets via `copy-webpack-plugin`?

Would you recommend this approach 

or 

do you expect to skip `copy-webpack-plugin`, create a new entrypoint, use require.context, import all and go through loaders to export all shared assets out?

**Comment by strarsis** [comment]
@kimyu92: Are you using [`copy-webpack-plugin`](https://webpack.js.org/plugins/copy-webpack-plugin/) and [`webpack-assets-manifest`](https://www.npmjs.com/package/webpack-assets-manifest)? Together the assets should be copied and also added to the manifest.

**Comment by kimyu92** [comment]
> @kimyu92: Are you using [`copy-webpack-plugin`](https://webpack.js.org/plugins/copy-webpack-plugin/) and [`webpack-assets-manifest`](https://www.npmjs.com/package/webpack-assets-manifest)? Together the assets should be copied and also added to the manifest.

Yes. I'm using both [copy-webpack-plugin](https://webpack.js.org/plugins/copy-webpack-plugin/) and [webpack-assets-manifest](https://www.npmjs.com/package/webpack-assets-manifest). 

You're absolutely right about the entries! I have also noticed that assets being copied by the plugin can be merged with assets loaded via asset modules

Output:
https://github.com/kimyu92/webpack-assets-manifest-copy-webpack-plugin#output
Config:
https://github.com/kimyu92/webpack-assets-manifest-copy-webpack-plugin/blob/main/webpack.config.js
