### ISSUE TITLE
Merging should not customize assets

### ISSUE THREAD

**Issue by delambo** [webdeveric/webpack-assets-manifest#17]
## The problem

Merge is calling `customize` resulting in assets being customized twice.

## Technical details

`processAssets` calls `set` which calls `customize`. That's good. But when you try to `maybeMerge` it also uses `set` which results in another call to `customize`.

### Webpack version

3.1.0

### Webpack config

If my description isn't enough, I'll try to piece together my config (I'm using kyt). Here's the [commit](https://github.com/NYTimes/kyt/pull/522/files#diff-291b6aa993c8d487d206a71d59b29218R56) I'm working on right now.

### Operating system

OSX 10.11.3

**Comment by webdeveric** [comment]
Can you provide a sample output file?

`set` is only called during `maybeMerge` when the `key` does not exist in `assets`.
See [WebpackAssetsManifest.js#L277](https://github.com/webdeveric/webpack-assets-manifest/blob/fb30ef17fa1c20d37a0a328181583ec7b847d904/src/WebpackAssetsManifest.js#L277)

**Comment by webdeveric** [comment]
@delambo I've updated the merge behavior. 

- `merge: false` - No change.
- `merge: true` - It will copy the existing keys/values without modification.
- `merge: 'customize'` - Allows customize during merge.

  Example:

  ```js
  new WebpackAssetsManifest({
    merge: 'customize',
    customize: function(key, value, originalValue, manifest) {
      if ( manifest.isMerging ) {
        // Do something
      }
    },
  });
  ```

Can you try it out and see if it resolves your issue?
It hasn't been published yet so you'll have to get it from Github.

```shell
npm i webdeveric/webpack-assets-manifest#dev
```

**Comment by delambo** [comment]
@webdeveric - Sorry, I found another solution and worked around this problem since I can uniquely test for my server assets. From the sound of it, that sounds like a good solution. I think a user should be able to opt out of customizing an asset during merge.
