### ISSUE TITLE
When running webpack 5 in development mode most files are missing from the manifest

### ISSUE THREAD

**Issue by thasmo** [webdeveric/webpack-assets-manifest#172]
## The problem
When running `webpack 5` in `development` mode, lots of files are missing from the manifest file. This is not an issue with `webpack 4` and an earlier version of `webpack-assets-manifest`. I would assume that files using the new `asset module` feature are the files missing in the manifest file.

Thanks for your great work on this plugin! :+1:

## Technical details
`webpack --mode production`
All files are listed. :heavy_check_mark:
```json
{
  "icons/linkedin.svg": "/static/icons/linkedin.6993445b.svg",
  "icons/twitter.svg": "/static/icons/twitter.459d91e0.svg",
  "icons/youtube.svg": "/static/icons/youtube.a5bc45ee.svg",
  "assets/icon.png": "/static/assets/icon.b02cb6b1.png",
  "assets/icon.svg": "/static/assets/icon.35f84bce.svg",
  "assets/logo.svg": "/static/assets/logo.1a4535a7.svg",
  "main.js": "/static/main.c0c99a31.js",
  "runtime.js": "/static/runtime.ad933a3d.js",
  "chunks/708.92302639.js": "/static/chunks/708.92302639.js",
  "chunks/538.3b0eb43a.js": "/static/chunks/538.3b0eb43a.js",
  "chunks/930.693cacfd.js": "/static/chunks/930.693cacfd.js",
  "styles.css": "/static/styles.4c60981e.css",
  "vendor.js": "/static/vendor.3cacb3b4.js",
  "entrypoints": {
    "main": {
      "assets": {
        "js": [
          "/static/runtime.ad933a3d.js",
          "/static/vendor.3cacb3b4.js",
          "/static/main.c0c99a31.js"
        ],
        "css": [
          "/static/styles.4c60981e.css"
        ]
      }
    }
  }
}
```

`webpack --mode development`
Asset files are missing. :x:
```json
{
  "main.js": "/static/main.js",
  "runtime.js": "/static/runtime.js",
  "vendor.js": "/static/vendor.js",
  "entrypoints": {
    "main": {
      "assets": {
        "js": [
          "/static/runtime.js",
          "/static/vendor.js",
          "/static/main.js"
        ]
      }
    }
  }
}
```

### Webpack version
`5.46.0`

### Operating system
Linux, Ubuntu

**Comment by webdeveric** [comment]
@thasmo Please provide your webpack config.

**Comment by thasmo** [comment]
@webdeveric While trying to create a simple reproduction case, I figured that the issue was related to a mis-configuration of `ts-node` on my side. By (wrongly) using the `--files` option of `ts-node`, it seems that `ts-loader` transpiles all existing `ts` files by itself, other than transpiling the actual bundle files given by webpack - that somehow leads to missing asset files. Not sure why this would only happen via `development` mode though.

Thanks for your time!
