### ISSUE TITLE
writeToDisk doesn't seem to be working

### ISSUE THREAD

**Issue by philipwalton** [webdeveric/webpack-assets-manifest#19]
I have multiple build processes going on at the same time, so I need to do asset revision management myself (and thus don't need this plugin to write the results to disk, just give me the filenames so I can do it myself).

The documentation says the `writeToDisk` option defaults to false, but when I add this plugin to my list of webpack plugins, it always outputs a file with the name `manifest.json` in my output directory.

Even if I explicitly set `writeToDisk` to false, it still writes a file.

Am I missing something or is this a bug?

**Comment by webdeveric** [comment]
@philipwalton The manifest file is always emitted like any other asset. The `writeToDisk` option exists for when you're using webpack-dev-server and you need the file to be actually written to disk and not only kept in memory.

If you have a custom build process and you want to handle writing the file yourself, you can use the `done` event. See the [example in the readme](https://github.com/webdeveric/webpack-assets-manifest#customizing-the-manifest).
