### ISSUE TITLE
How to get asset size within transform callback? (Webpack v5)

### ISSUE THREAD

**Issue by yvele** [webdeveric/webpack-assets-manifest#198]
## The problem

I used to get asset size within [transform callback](https://github.com/webdeveric/webpack-assets-manifest#transform) using `manifest.stats.assets` but now with Webpack v5 and webpack-assets-manifest v6 the `manifest.stats` property is undefined.

```js
new WebpackAssetsManifest({
  output : "main.hapticmedia-manifest.json",
  space : config.minifyManifest ? 0 : 2,
  publicPath : true,
  transform : (assets, manifest) => manifest.stats.assets
    .filter(({ name }) => !name.match(/\.map$/)) // Exclude source maps
    .map(({ name, size }) => ({
      url : assets[manifest.assetNames.get(name)] || `${publicPath}${name}`,
      size // Size in bytes
    }))
})
```

I would like to know what is the new way to get asset size 🤔 

### Webpack version

- Webpack v5.61.0
- webpack-assets-manifest v6.4.0

### Operating system

MacOS

**Comment by webdeveric** [comment]
@yvele You can use the `customize` hook. https://github.com/webdeveric/webpack-assets-manifest/blob/2ec37f6106d3d2b1f82de5334b3c0e787eadee64/examples/customized.js#L6

The `asset` parameter is the asset object from webpack. There is a `size()` method you can call to get the file size.

**Comment by yvele** [comment]
> @yvele You can use the `customize` hook.
> 
> https://github.com/webdeveric/webpack-assets-manifest/blob/2ec37f6106d3d2b1f82de5334b3c0e787eadee64/examples/customized.js#L6
> 
> The `asset` parameter is the asset object from webpack. There is a `size()` method you can call to get the file size.

Thank you for your quick answer!

Unfortunately it looks like there is no `asset.size()` method 🤔 

```js
new WebpackAssetsManifest({
  output : "main.hapticmedia-manifest.json",
  space : config.minifyManifest ? 0 : 2,
  publicPath : true,
  customize(entry, original, manifest, asset) {
    // Exclude source maps
    if (entry.key.match(/\.map$/i)) {
      return false;
    }
    return {
      // Absolute URL
      url : `${publicPath}${entry.value}`,
      // Size in bytes
      size : asset.size() // <----------- HookWebpackError: asset.size is not a function
    };
  }
})
```

I've console logged `entry`, `original` and `asset`:

```js
entry {
  key: 'dpdb.json',
  value: 'https://static.snd.apviz.io/trigon/sandbox/c3da6345135b1074803ebefb3536316d.json'
}
original { key: 'dpdb.json', value: 'c3da6345135b1074803ebefb3536316d.json' }
asset {
  name: 'c3da6345135b1074803ebefb3536316d.json',
  source: CachedSource {
    _source: RawSource {
      _valueIsBuffer: true,
      _value: <Buffer 7b 22 66 6f 72 6d 61 74 22 3a 31 2c 22 6c 61 73 74 5f 75 70 64 61 74 65 64 22 3a 22 32 30 31 39 2d 30 34 2d 32 35 54 32 33 3a 34 38 3a 33 33 5a 22 2c ... 13460 more bytes>,
      _valueAsBuffer: <Buffer 7b 22 66 6f 72 6d 61 74 22 3a 31 2c 22 6c 61 73 74 5f 75 70 64 61 74 65 64 22 3a 22 32 30 31 39 2d 30 34 2d 32 35 54 32 33 3a 34 38 3a 33 33 5a 22 2c ... 13460 more bytes>,
      _valueAsString: undefined
    },
    _cachedSourceType: undefined,
    _cachedSource: <Buffer 7b 22 66 6f 72 6d 61 74 22 3a 31 2c 22 6c 61 73 74 5f 75 70 64 61 74 65 64 22 3a 22 32 30 31 39 2d 30 34 2d 32 35 54 32 33 3a 34 38 3a 33 33 5a 22 2c ... 13460 more bytes>,
    _cachedBuffer: undefined,
    _cachedSize: 13510,
    _cachedMaps: Map(0) {},
    _cachedHashUpdate: undefined
  },
  info: { immutable: true, sourceFilename: 'src/helpers/device/dpdb.json' }
}
```

**Comment by webdeveric** [comment]
@yvele Try `asset.source.size()`

**Comment by webdeveric** [comment]
[Example added](https://github.com/webdeveric/webpack-assets-manifest/blob/61e6142a23c5d966abc26b515000ae4a883beff8/examples/asset-size.js)
