### ISSUE TITLE
How can I compile twbs (main issue is scss) using webpack-assets-manifest?

### ISSUE THREAD

**Issue by theacastus** [webdeveric/webpack-assets-manifest#20]
Well, I don't have a problem. I have a question. I want to use Bootstrap (Twitter bootstrap) with webpack, which requires sass-loader, postcss-loader and autoprefixer. But instead of these, I want to use manifest. The webpack-manifest-plugin seem to not support SCSS in a way I want to, but this plugin looks better to me. 

Can you help me with that please ? I am not Node or JS dev. I work in PHP but I wanted to learn something new. So I decided to use webpack in a project I am currently working on. And it get me some issues, this is the last one... but the most important! :D

Thank you for your time and advices =)

**Comment by webdeveric** [comment]
@theacastus This plugin does not do any transforming of code like babel or node-sass. It only records the results of a Webpack build.

The [Webpack documentation ](https://webpack.js.org/concepts/) is a good place to start. There are also plenty of [webpack boilerplate repos](https://github.com/search?utf8=%E2%9C%93&q=topic%3Awebpack+topic%3Aboilerplate) on Github you should checkout.

**Comment by theacastus** [comment]
@webdeveric Thank you, obviously I have missed the whole point of it. f... Thank you, I am going straight for the docs!
