### ISSUE TITLE
Add only entrypoints to manifest

### ISSUE THREAD

**Issue by niksy** [webdeveric/webpack-assets-manifest#210]
## The problem

Currently plugin adds all chunks to manifest, but I’m looking for a way to add only entrypoints. I’ve tried different options but couldn’t get this to work.

## Technical details

Latest plugin version, latest Webpack.

**Comment by webdeveric** [comment]
There are a few options around `entrypoints`. Basically, you should turn it on, then `transform` the manifest to discard what you don't want.

https://github.com/webdeveric/webpack-assets-manifest#entrypoints
https://github.com/webdeveric/webpack-assets-manifest#transform

This example will only keep the `entrypoints` data. You should update it to meet your specific needs.

```js
new WebpackAssetsManifest({
  entrypoints: true,
  transform(assets, manifest) {
    return assets[manifest.options.entrypointsKey];
  },
});
```
