### ISSUE TITLE
request addition of support for 'renamed assets'

### ISSUE THREAD

**Issue by pgnd** [webdeveric/webpack-assets-manifest#219]
When generating hashed-asset manifest in conjunction with image-minimizer-webpack-plugin, when using the 'generator' capability of on-the-fly image conversion (e.g. png -> webp) during webpack5 build, the generated assets are incorrectly added to manifest WITH '[hash]' in the key, rather than simply in the value,

This apparently is due to lack of support for 'renamed assets' in webpack-assets-manifest,

https://github.com/webpack-contrib/image-minimizer-webpack-plugin/issues/302#issuecomment-1031480876

Requesting addition of that support, here.

**Comment by webdeveric** [comment]
@pgnd Can you provide a minimal reproducible example that shows the error so I can clone and run locally?

**Comment by pgnd** [comment]
Sure, might take a little bit.
I have to strip down my production instance, where I see this, to something I can actually share -- & reproduces.

**Comment by pgnd** [comment]
@webdeveric 

minimal-ish ...

```
git clone https://github.com/pgnd/test01.git
cd test01

composer -V
	Composer version 2.2.6 2022-02-04 17:00:38
yarn -v
	3.2.0-rc.14

tree resources_loc/assets/img/
	resources_loc/assets/img/
	└── TEST.png

composer update
yarn yarn wp:p

tree public/build
	public/build
	├── assets-manifest.json
	├── css
	│   └── main.f5ec4099762cb973803c.css
	├── img
	│   └── TEST.d3453ac871872dfc247c.webp
	└── js
		├── jquery.d5ef39ee3fa7fd7b52e0.js
		├── main.d114c4246caac44beaef.js
		├── runtime_manifest.4d2fc54bcca35228e417.js
		└── vendor.04be37cfe5b7a4859c78.js

cat public/build/assets-manifest.json
	{
!!	"TEST.d3453ac871872dfc247c.webp": "/build/img/TEST.d3453ac871872dfc247c.webp",
	"jquery.js": "/build/js/jquery.d5ef39ee3fa7fd7b52e0.js",
	"main.css": "/build/css/main.f5ec4099762cb973803c.css",
	"main.js": "/build/js/main.d114c4246caac44beaef.js",
	"runtime_manifest.js": "/build/js/runtime_manifest.4d2fc54bcca35228e417.js",
	"vendor.js": "/build/js/vendor.04be37cfe5b7a4859c78.js"
	}
```
	
NOTE, the key
```
TEST.d3453ac871872dfc247c.webp
```

should be
```
TEST.webp
```

**Comment by pgnd** [comment]
@webdeveric 

any more info needed here?  or just, still waiting on webpack-contrib/image-minimizer-webpack-plugin#304 ?
