### ISSUE TITLE
preload and prefetch not present in the manifest entrypoints with v4.x.x

### ISSUE THREAD

**Issue by xtroncode** [webdeveric/webpack-assets-manifest#224]
## The problem

The master readme says v4 entrypoints structure includes preload and prefetch but that does not seem to be working also the readme under tag v4.0.6 does not mention this. How to get it working?

## Technical details
preload and prefetch not present in the manifest entrypoints but is mentioned in the readme.

### Webpack version
4

### Operating system
Windows

**Comment by webdeveric** [comment]
@xtroncode Are you doing what is described here? https://webpack.js.org/guides/code-splitting/#prefetchingpreloading-modules

**Comment by xtroncode** [comment]
Yes. Seems to be working while trying to reproduce this in a new project, might be some other issue. Will try to figure out. Closing this for now. Thanks.
