### ISSUE TITLE
Question: How to handle the fact, that other plugins need the content of manifest.json?

### ISSUE THREAD

**Issue by mischah** [webdeveric/webpack-assets-manifest#23]
Hej, I guess I might have an unusual use case 😆

## The problem
I have a plugin which needed the filenames generated by `webpack-assets-manifest`.

I read that plugins are applied in the order they are defined in the `plugins` array of the Webpack config. So I try to `require('../.manifest.json');` in the plugin which is defined after `webpack-assets-manifest`. But this fails. Probably because of a lifecycle / async / timing problem.

## Technical details

I used the `done` callback to generate some output via `console.log()` There you can see, that the console output from the plugin following `webpack-assets-manifest` is first. See Webpack config

![image](https://user-images.githubusercontent.com/441011/35391401-e2da2a8a-01de-11e8-9774-d4510582f2f6.png)

I need to use the transform method of `CopyWebpackPlugin` to apply the chunkhash to the resources in my html files for cache busting.

I know this is a bit unusual and there are many usecases where one easily could use the Webpack HTML-Plugin. But I’m not using my Webpack config for a single page application but for multiple HTML files generated by handlebars.

Do you have any idea how to solve my problem?

Thanks, Michael

### Webpack version
3.10.0

### Webpack config

Here is an extract of my config. Let me know if you need to see more.

```javascript
plugins: [
  new WebpackAssetsManifest({
    writeToDisk: true,
    output: path.resolve('.webpack-assets.json'),
    done(manifest) {
      console.log(chalk.cyan('\n⏰  Here we are in the done() method of WebpackAssetsManifest'));
      console.log(`\nThe manifest has been written to ${manifest.getOutputPath()}`);
    }
  }),
  generateCssFile,
  new webpack.optimize.CommonsChunkPlugin({name: ['app', 'vendor', 'polyfills']}),
  new webpack.ProvidePlugin({...configFile.webpack.ProvidePlugin}),
  new CopyWebpackPlugin([
    {
      from: '**/*.html',
      context: useHandlebars ? settings.destinations.handlebars : './src',
      transform(content) {
        const assets = require('../.webpack-assets.json');
        console.log(chalk.magenta('\n⏰  Here we are in the transform() method of CopyWebpackPlugin'));
        content = content.toString();
        content = content.replace(/@@(.*\.css|.*\.js)/g, (match, $1) => assets[$1]);
        return content;
      }
    },
    {
      from: '**/*',
      context: settings.sources.assets,
      to: settings.destinations.assets,
      ignore: ['scss/**']
    }
  ])
]
```
### Operating system
Mac OS 10.12.6

**Comment by mischah** [comment]
Just pushed the current non working status to a branch in case you’d like to see it in action:
https://github.com/micromata/Baumeister/tree/webpack-assets-manifest

**Comment by webdeveric** [comment]
@mischah I looked at your code and made a small update to `webpack.base.babel.js` which seemed to work. With `webpack-assets-manifest`, you can access the `assets` property directly to see what will be in the json output.

Relevant parts below. Let me know if that works for you.

```
//... 

const manifest = new WebpackAssetsManifest({
    output: path.resolve('.webpack-assets.json'),
});

// ...

module.exports = (options) => ({
    //...
    plugins: [
        manifest,
        new CopyWebpackPlugin([
            {
                from: '**/*.html',
                context: useHandlebars ? settings.destinations.handlebars : './src',
                transform(content) {
                    return content.toString().replace(/@@(.*\.css|.*\.js)/g, (match, $1) => manifest.assets[$1] || $1);
                }
            },
            {
                from: '**/*',
                context: settings.sources.assets,
                to: settings.destinations.assets,
                ignore: ['scss/**']
            },
            ...copyVendorFiles
        ]),
        ...options.plugins
    ],
    // ...
});
```

**Comment by mischah** [comment]
@webdeveric It just works. Thank you so much 💖 

So I guess, accessing file-system was the bootle neck. Good to know.
