### ISSUE TITLE
Feature entrypoint dependency listings in the manifest

### ISSUE THREAD

**Issue by tdd** [webdeveric/webpack-assets-manifest#24]
Hey Eric!

Thanks for keeping this plugin up-to-date so I can use it with v4! 👏 

## The problem

The manifest currently only maps individual chunks to their final paths. But because of bundle/code splitting (which is automatic in Webpack 4 when setting `optimization.splitChunks.chunks` to `'all'`, a godsend), when I want to load "what I need for entrypoint X", I need to know the multiple JS/CSS initial chunks this requires, much like `HtmlWebpackPlugin` does.

## Technical details

This information is available in the compiler's `compilation.entrypoints` data structure. We can iterate on this right before emit, building JS and CSS initial chunk lists for each entry point, and augment the manifest with a configurable key (say, defaulting to `entryPoints`) that lists this.  From then on, it's a simple matter of using that in our server side to generate the relevant `<link/>` and `<script>` tags.

**I implemented this already** as a `done` callback (so I re-read and re-write the file, as it's been emitted already) in a project of mine, and would be willing to turn that into a fleshed-out PR with various tests if you're interested and we can converge on an API and defaults for this.

What say you?

### Webpack version

4+

### Webpack config

```js
{
  optimization: {
    runtimeChunk: true, // while we're at it, might as well extract it too.
    splitChunks: {
      chunks: 'all'
    }
  }
}
```

### Operating system

All.

**Comment by webdeveric** [comment]
Can I see your `done` callback and some sample output of the `manifest.json`?

**Comment by tdd** [comment]
Sure thing. Right now I filter (both for the base manifest entries and my extra output) on CSS+JS, as fonts etc. are not referenced from the HTML in any way. But here goes:

```js
// In my webpack.config.parts.js

exports.publishManifest = () => {
  const ManifestPlugin = require('webpack-assets-manifest')

  return {
    plugins: [
      new ManifestPlugin({
        customize: retainOnlyJSAndCSS, // Besides the point of the current issue, but just FYI
        done: augmentManifestWithEntrypoints,
        publicPath: true,
      }),
    ],
  }
}

// …

// Manifest helper functions
// -------------------------

// If the plugin handled this, we wouldn't need to rewrite, we could take the existing
// manifest and set(…) in there pre-emit.
async function addEntrypointsToManifest(data, path) {
  const readFile = promisify(fs.readFile)
  const writeFile = promisify(fs.writeFile)
  const orig = JSON.parse(await readFile(path))
  orig.entryPoints = data
  await writeFile(path, JSON.stringify(orig, setsAsArrays, 2), {
    encoding: 'utf-8',
  })
  console.log(
    `[Manifest] Augmented manifest (with entrypoints data) written to ${path}`
  )
}

// This is the core issue.
function augmentManifestWithEntrypoints(manifest, stats) {
  // Stay consistent with the main behavior of the plugin's `publicPath` option.
  let prefix = manifest.options.publicPath
  if (prefix === true) {
    prefix = stats.compilation.options.output.publicPath
  }
  if (!prefix) {
    prefix = ''
  }
  // Accrue entry points chunk listing info
  const entrypoints = {}
  for (const [entry, { chunks }] of stats.compilation.entrypoints) {
    const files = chunks.reduce(
      (acc, { files }) => {
        for (const file of files) {
          if (file.endsWith('.js')) {
            acc.js.add(Path.join(prefix, file))
          } else if (file.endsWith('.css')) {
            acc.css.add(Path.join(prefix, file))
          }
        }
        return acc
      },
      { css: new Set(), js: new Set() }
    )
    entrypoints[entry] = files
  }

  // Update file
  addEntrypointsToManifest(entrypoints, manifest.getOutputPath())
}

const REGEX_SOURCE = /\.(?:css|jsx?)$/i

function retainOnlyJSAndCSS(key, value) {
  if (!REGEX_SOURCE.test(key)) {
    return false
  }

  return { key, value }
}

// Sets do not have a useful `toJSON()` implementation. Turn them into arrays.
function setsAsArrays(key, value) {
  if (value instanceof Set) {
    return [...value]
  }

  return value
}
```

Example output:

```js
{
  // Regular plugin output, then:
  "entryPoints": {
    "front": {
      "css": [
        "/assets/front.4ab3997f.css",
        "/assets/front.0533297b.css"
      ],
      "js": [
        "/assets/runtime~front.cf74b43b.js",
        "/assets/vendors~back~front.155f10bc.js",
        "/assets/vendors~front.be98dc1f.js",
        "/assets/front.031ae3be.js"
      ]
    },
    "back": {
      "css": [
        "/assets/vendors~back.94362573.css",
        "/assets/back.4ab3997f.css",
        "/assets/back.13e9dcd0.css"
      ],
      "js": [
        "/assets/runtime~back.5c0dfc64.js",
        "/assets/vendors~back~front.155f10bc.js",
        "/assets/vendors~back.9aa8440b.js",
        "/assets/back.17b32de3.js"
      ]
    }
  }
}
```

**Comment by webdeveric** [comment]
Thanks. I'll take a look this weekend.

**Comment by webdeveric** [comment]
@tdd I've added this functionality to my [`dev`](https://github.com/webdeveric/webpack-assets-manifest/tree/dev) branch.

```js
new WebpackAssetsManifest({
  entrypoints: true,
  entrypointsKey: 'entryPoints',
})
```

`entrypointsKey` defaults to `entrypoints` and can be set to `false` if you want the entrypoints to be at the root of the manifest.json.

Let me know if that works for you.

**Comment by tdd** [comment]
Hey @webdeveric that's awesome!

I'm in the middle of another feature dev right now and don't want to stash and branch, but I'll be giving it a whirl later today or tomorrow and let you know. Implementation looks good at any rate.

Best,

**Comment by tdd** [comment]
Hey @webdeveric!

Sorry it took me a bit longer to try this out. Just did, and it works just fine, I get the exact same results than I did with my custom tweaks.

Now all I need is an updated `latest` tag on npm 😉 

Thanks a ton!

**Comment by webdeveric** [comment]
I'll try to release the next version this week. I've updated some stuff and I need to write some tests.

**Comment by tdd** [comment]
Hey @webdeveric!

Can't wait to see this on npm.

It seems like you occasionally force-push to `dev`, which removes its former commits from accessible history and makes our installs break (`package-lock.json` will store whatever head commit the `package.json`-referenced branch was on, and npm will re-install from there).

Best,
