### ISSUE TITLE
Handling async chunks from `splitChunks`?

### ISSUE THREAD

**Issue by leebenson** [webdeveric/webpack-assets-manifest#25]
Using Webpack 4, this plugin works perfectly with sync chunks, but doesn't handle async chunks generated by `import()` statements.

A dump of my `manifest.json`:

```
{
  "assets/img/logo.png": "assets/img/logo.png",
  "main.css": "assets/css/main.d41d8cd98f00b204e9800998ecf8427e.css",
  "main.css.map": "assets/css/main.d41d8cd98f00b204e9800998ecf8427e.css.map",
  "main.js": "assets/js/main.530c2d547d428f017101.js",
  "main.js.map": "assets/js/main.530c2d547d428f017101.js.map"
}
```

But on the filesystem:

<img width="352" alt="screen shot 2018-03-05 at 11 12 35" src="https://user-images.githubusercontent.com/719722/36972216-3a2d4f38-2066-11e8-9323-e45998745f78.png">

**Comment by webdeveric** [comment]
@leebenson I looked into this a long time ago (Webpack v1) and from what I can remember, it wasn't possible/feasible to get a name for chunks loaded with `require.ensure` (now `import()`). And since async chunks are loaded from other files (`main.530c2d547d428f017101.js` in your example) and not loaded directly with a `<script>` tag, I didn't see the need to include them in the `manifest.json`.

Assuming I can get the async chunk URLs into the manifest, how would you use them? Maybe there is a valid reason I can't think of at the moment.

**Comment by webdeveric** [comment]
@leebenson After looking into this a bit, I've found that you can opt-in to having your async chunks included in the `manifest.json` by providing a `webpackChunkName` comment in the [`import()`](https://webpack.js.org/api/module-methods/#import-). I'm still looking at it to see if this can be automated.

Example: 
```js
import(/* webpackChunkName: "[request]" */ './some-file.js');
```

**Comment by persocon** [comment]
I saw that it goes to the root of the manifest, is it possible to include it to the entrypoint it belongs?
the idea behind it is to make custom prefetch of assets

**Comment by mxmul** [comment]
+1 for associating the async chunks with their entrypoints somehow. I'd like to do something similar to [GoogleChromeLabs/preload-webpack-plugin](https://github.com/GoogleChromeLabs/preload-webpack-plugin) in my application, but it's this plugin doesn't currently tell me which assets should be preloaded/prefetched for a given entrypoint.

**Comment by huzhongchun** [comment]
Have you resolve this problem? @leebenson

**Comment by pavelloz** [comment]
https://github.com/danethurber/webpack-manifest-plugin - this plugin seems to do it pretty good

**Comment by mxmul** [comment]
For my specific use-case (preloading React components in async chunks), the [@loadable](https://github.com/smooth-code/loadable-components) library solved the problem (specifically the SSR integration).
