### ISSUE TITLE
Merging with existing manifest.json

### ISSUE THREAD

**Issue by niksy** [webdeveric/webpack-assets-manifest#3]
When you have multiple build processes (e.g. Gulp tasks for images) which generate manifest.json file without using Webpack, it would be nice if that existing manifest.json is merged with the one generated with this plugin. Could this be added as an option?

**Comment by webdeveric** [comment]
@niksy I'll look into adding that feature.

Can you provide some more details about your build process?
Do you run webpack from gulp?
Have you tried merging json files with [gulp-merge-json](https://www.npmjs.com/package/gulp-merge-json)?

**Comment by QWp6t** [comment]
Webpack has an example for running multiple compilers: https://github.com/webpack/webpack/tree/master/examples/multi-compiler

This plugin in its current state wouldn't work correctly with that setup.

A similar plugin to this one supports it with a `cache` option, which the user can supply an object literal: https://github.com/danethurber/webpack-manifest-plugin#configuration

**Comment by webdeveric** [comment]
@QWp6t I was going to add multi compiler support soon and passing in a shared object is probably the easiest way to do it.

I'm not sure multi compiler support will help @niksy since he is using Gulp to process images, not webpack. It might work if he uses Gulp to run webpack though.

**Comment by QWp6t** [comment]
I was thinking that in the same way that the manifest object would be passed between compilations, it could be passed as an option during an initial compilation as well, i.e., if he processes his images with gulp first (which it sounds like he's doing), he could then pass `require('path/to/manifest.json')` as an option to this plugin, and it would treat it similar to how it would be treated between compilations.  I hope that makes sense.

That's what was going on in my head when I made that post. Would that work or nah?

**Comment by webdeveric** [comment]
My first thought was to add an option to prepopulate what goes in `manifest.json`.
Maybe something like `{data: require('images.json')}`.

**Comment by niksy** [comment]
@webdeveric My current process compiles CSS files and creates manifest file with [gulp-rev](https://github.com/sindresorhus/gulp-rev). Same goes for images. gulp-rev has option to merge existing manifest.json file in case of multiple Gulp processes creating manifest file.

If I’m compiling JS files through Gulp, I could also use gulp-rev, and in case of Webpack, use it through [webpack-stream](https://github.com/shama/webpack-stream), but that seems rather inconvenient since this plugin could also handle that situation with proposed merge option, and in case of multi-compiler support, it would be preferable I suppose.

The other case this could be useful is watch mode. If you compile and watch CSS and image files with Gulp and create manifest file with gulp-rev, and compile and watch JS files with Webpack and create manifest file with this plugin, in case of Webpack manifest file will be overwritten on every emitted change, as opposed to gulp-rev where it would be merged.

Is this understanble?

**Comment by webdeveric** [comment]
@niksy Yes, that makes sense. The `merge` option sounds fine.

**Comment by webdeveric** [comment]
@niksy I've added a `merge` option. It is currently in the `dev` branch.
If you'd like to try out that version, you can run `npm i webdeveric/webpack-assets-manifest#dev` to install it.

**Comment by niksy** [comment]
@webdeveric Tried it and works as advertised :+1:
