### ISSUE TITLE
option transform render at the end of manifest

### ISSUE THREAD

**Issue by jimblue** [webdeveric/webpack-assets-manifest#31]
## The problem

What's done with transform option always render at the end of manifest.
Even if the name start with *a*.
I've also try to unshift, nothing works. 😭

<img width="760" alt="screen shot 2018-04-19 at 02 17 38" src="https://user-images.githubusercontent.com/10623367/38964602-dd215b60-4377-11e8-85bd-fcb67ea3a452.png">

### Webpack version

webpack version **4.6.0**

### Webpack config

```js
new WebpackAssetsManifest({
        transform (assets, manifest) {
          // Theme infos
          const { key, value } = manifest.hooks.customize.call({
            key: '__________THEME__________',
            value: {
              name: Config.themeName,
              version: Config.themeVersion,
              description: Config.themeDescription
            }
          })

          assets[key] = value
        },
        customize (entry, original, manifest, asset) {
          // Prevent adding sourcemap to the manifest
          if (entry.key.toLowerCase().endsWith('.map')) {
            return false
          }
        }
      })
```
### Operating system

Mac OSX version **10.13.4**

**Comment by webdeveric** [comment]
`assets` is an object so adding new properties will put them at the end when JSON stringified.
If you want to add properties to the top of the manifest, something like this should work.

```js
new WebpackAssetsManifest({
  transform (assets, manifest) {
    const entries = {
      __________THEME__________: {
        name: Config.themeName,
        version: Config.themeVersion,
        description: Config.themeDescription,
      },
      anotherProperty: 'some value',
    };

    return Object.assign( entries, assets );
  },
})
```

**Comment by jimblue** [comment]
Awesome thank you so much @webdeveric !
