### ISSUE TITLE
entryPoints does not filter async from initial chunks

### ISSUE THREAD

**Issue by JSteunou** [webdeveric/webpack-assets-manifest#38]
## The problem
Following this issue https://github.com/webdeveric/webpack-assets-manifest/issues/24 all chunks are listed in entrypoints, but only those required for the initial load are truly needed.
The problem is when using this list to generate our own html file, too many js files are loaded. I have a build with 7 chunks listed for 1 entry point, but only one is truly needed at initial load. The others are async and handled by webpack when needed.
This produce a 1st load bottle-neck and I end up re-writing the `entrypoints` property myself in the `done` hook

## Technical details
Look at https://webpack.js.org/api/stats/#chunk-objects and https://webpack.js.org/plugins/split-chunks-plugin/#splitchunks-chunks

A simple filter on `chunk.initial` property would do the trick. In order to be not breaking I advice to add an plugin option to activate it.

### Webpack version
latest 4 at this time

**Comment by JSteunou** [comment]
This is unexpected but it seems that all the chunks I had where in fact necessary, so it seems the list is already filter. My bad :sweat:

**Comment by pxwee5** [comment]
Reviving this. 
Can we get this feature please? It'll be nice to only include initial chunks in the manifest and not everything in the project.
