### ISSUE TITLE
Invalid manifest with the latest mini-css-extract-plugin

### ISSUE THREAD

**Issue by renchap** [webdeveric/webpack-assets-manifest#39]
After updating `mini-css-extract-plugin` from 0.4.2 to 0.4.3, the manifest is no longer valid.
Assets referenced via the CSS are missing, and some assets are pointing to unrelated paths. For example (from the issue below):

With 0.4.2:
`"images/create/wallet.png": "images/create/wallet.png"`

With 0.4.3
`"images/create/Create.scss": "images/create/wallet.png"`

See https://github.com/webpack-contrib/mini-css-extract-plugin/pull/177#issuecomment-423111163

[According to @evilebottnawi](https://github.com/webpack-contrib/mini-css-extract-plugin/pull/177#issuecomment-423111701) this is a problem with the manifest plugin, not the referenced change.

**Comment by webdeveric** [comment]
@renchap I'm using `module.userRequest` to get the original filename and it is wrong when using `mini-css-extract-plugin` `0.4.3`. Its fine in `0.4.2` and below. Its being set to the css file instead of the asset (bg image, font, etc.). The other loaders I'm using have the expected value for `module.userRequest`.

I tried another webpack manifest plugin and I get the same result. This issue is not isolated to my plugin.

**Comment by piecyk** [comment]
@webdeveric had a quick look, maybe this approach is better? It looks like it fixes the issue also all your test pass 🤔 IMHO using `module.identifier()` is much safer, what do you think ? 

https://github.com/piecyk/webpack-assets-manifest/commit/2e07ad92c4eda363259b98fc6e946cc7b18175cc

**Comment by piecyk** [comment]
Hmm maybe even simpler, only set name and originalName when extensions match

https://github.com/piecyk/webpack-assets-manifest/commit/5dcba5cd9436fd3c4b28e6c4a820e3ee6172fcb0

**Comment by webdeveric** [comment]
@piecyk I'm trying it out locally. It looks promising.

**Comment by webdeveric** [comment]
@renchap I have a fix in my `dev` branch.

Can you try it out and let me know how it works for you?

```shell
npm install https://github.com/webdeveric/webpack-assets-manifest.git#dev
```

**Comment by renchap** [comment]
Seems to work fine for me! 👍

**Comment by webdeveric** [comment]
@renchap The updated version has been published to npm.

**Comment by piecyk** [comment]
Good work @webdeveric 👍
