### ISSUE TITLE
Just output filenames

### ISSUE THREAD

**Issue by JPOak** [webdeveric/webpack-assets-manifest#43]
I am using the MiniCssExtractPlugin and I am I have the Output like so:

```
new MiniCssExtractPlugin({
  filename: '../styles/[name]_[contenthash].css'
}),
```

Thus In my manifest.json it outputs like:

```
{
  "main.css": "../styles/main_4602f108edba94052271.css",
  "main.js": "main_3cd70220ab04fa1f301f.js"
}
```
I would like to have only the file name for the css instead of the entire output path. I did not see an option to just print out filenames. Is this possible? Maybe this is more of a MiniCssExtractPlugin issue as it doesn't seen to have a separate Output option.

**Comment by webdeveric** [comment]
@JPOak This can be done using the `customize` hook ([example](https://github.com/webdeveric/webpack-assets-manifest/blob/3969c120a28b8d56838c608e54ec25560c2d08db/examples/customized.js#L6)).

Something like this should work (untested and quickly written).

```js
const path = require('path');

const manifest = new WebpackAssetsManifest({
  customize(entry, original, manifest, asset) {
    entry.value = path.basename( entry.value );
  },
});
```

**Comment by JPOak** [comment]
@webdeveric That looks like it worked. Thanks so much.
