### ISSUE TITLE
Prevent stringify for manifest trasformation

### ISSUE THREAD

**Issue by ydegtyar** [webdeveric/webpack-assets-manifest#45]
Can't transform manifest into static PHP class for memory optimizations. After the write, the class has \n instead of line separators and double quotes at the beginning and in the end. Can I prevent JSON.stringify function to write file different from json?

**Comment by webdeveric** [comment]
@ydegtyar This plugin currently only outputs a JSON document and was not intended to work that way.
Maybe I can help come up with a workaround. Can you show me your code?

**Comment by webdeveric** [comment]
Closing due to no response.
