### ISSUE TITLE
`output` option does not respect directories

### ISSUE THREAD

**Issue by philipnilsson** [webdeveric/webpack-assets-manifest#46]
## The problem

I've configured webpack-assets-manifest as

```js
new WebpackAssetsManifest({
    output: '/js/manifest.json'   
});
```

however the manifest appears in the root when I run `webpack-dev-server`. 

This is a problem for me re: migrating from `webpack-manifest-plugin` for my existing app that expects a manifest in this folder.

### Webpack version

4.20.2

### Operating system

MacOS Mojave (10.14.2)

**Comment by webdeveric** [comment]
@philipnilsson have you tried using `writeToDisk: true` and using an absolute path for your `output` option? Maybe something like `path.join(__dirname, '/your/path/manifest.json')`.

If that doesn't work for you, can you post your webpack config so I can get it running locally?

**Comment by webdeveric** [comment]
Closing due to no response.
