### ISSUE TITLE
Etrypoints being overwritten in multi-compiler mode

### ISSUE THREAD

**Issue by somebody32** [webdeveric/webpack-assets-manifest#48]
## The problem
When using assets-manifest plugin for the multi-compiler webpack configuration I can share assets between manifests and it works great. 

But if I add `entrypoints` option only entrypoints from the last compilation are stored. Am I doing something wrong or is it not supported yet?

Thanks in advance!

**Comment by webdeveric** [comment]
@somebody32 I noticed that and I have a fix locally but I'm also doing some other updates so its not ready yet.

You can prevent this by using the [entrypointsKey](https://github.com/webdeveric/webpack-assets-manifest#entrypointskey) option in one of your `WebpackAssetsManifest` instances.

**Comment by somebody32** [comment]
thank you @webdeveric! that is exactly what I'm doing now, but as soon as my config is wrapped with rails/webpacker it requires me to jump through some hoops :) Thanks again for your work!

**Comment by PikachuEXE** [comment]
@somebody32 
How do you workaround this issue?
I am trying to have multiple targets (one for ES5 one for ES2015)
But (rails/webpacker is hardcoded to use `entrypoints` to look up chunks)[https://github.com/rails/webpacker/blob/v4.0.1/lib/webpacker/manifest.rb#L21-L29]

**Comment by somebody32** [comment]
@PikachuEXE in my case the second target doesn't have multiple entrypoints that is why I've totally disabled it:
```js
const assetManifestPlugin = config.plugins.find(
  plugin => plugin instanceof WebpackAssetsManifest
);
const manifestDataSharing = Object.create(null);
assetManifestPlugin.options.assets = manifestDataSharing;

const backofficeConfig = { ...config };
backofficeConfig.optimization = { ...config.optimization };
backofficeConfig.optimization.splitChunks = false;
backofficeConfig.optimization.runtimeChunk = false;

backofficeConfig.plugins = [...config.plugins];
const pluginIndex = config.plugins.indexOf(assetManifestPlugin);
backofficeConfig.plugins[pluginIndex] = new WebpackAssetsManifest({
  assets: manifestDataSharing,
  entrypoints: false,
  integrity: false,
  writeToDisk: true,
  publicPath: true
});
return backofficeConfig;
```

**Comment by PikachuEXE** [comment]
@somebody32 
Thanks
I think I found a way to workaround it by replacing `setRaw` function
Let me post result later when I actually get it to work

**Comment by PikachuEXE** [comment]
My workaround/hack:
```js
// some_webpack_base_config.js
const { environment } = require("@rails/webpacker")

// Since we have multiple targets
// And webpacker only assume one manifest file
// We need to enable "merging"
// https://github.com/webdeveric/webpack-assets-manifest
const WebpackAssetsManifest = require("webpack-assets-manifest")
const webpack_assets_manifest_plugin_options = Object.assign({}, environment.plugins.get("Manifest").options)
// This is for sharing data for same plugin in 2 targets
const new_manifest_assets_date_store = Object.create(null)
webpack_assets_manifest_plugin_options.assets = new_manifest_assets_date_store
const new_webpack_assets_manifest_plugin = new WebpackAssetsManifest(webpack_assets_manifest_plugin_options)
const oldSetRaw = new_webpack_assets_manifest_plugin.setRaw
new_webpack_assets_manifest_plugin.setRaw = function(key, value) {
  const self = new_webpack_assets_manifest_plugin
  const entrypointsKey = self.options.entrypointsKey
  if (key === entrypointsKey && typeof entrypointsKey === "string") {
    const existing_entrypoints = self.get(entrypointsKey)

    if (typeof existing_entrypoints === "object" && existing_entrypoints != null) {
      const merged_entrypoints = Object.assign({}, existing_entrypoints || {}, value)
      oldSetRaw.call(self, key, merged_entrypoints)

      return
    }
  }

  oldSetRaw.call(self, key, value)
}

environment.plugins.append("Manifest", new_webpack_assets_manifest_plugin)

module.exports = {
  environment: environment,
}
```

**Comment by elstgav** [comment]
@webdeveric anything we can do to help get this merged in master?

**Comment by webdeveric** [comment]
This should be fixed in my `dev` branch. I'm updating this plugin for Webpack 5 support. I'll try to release an update soon.
