### ISSUE TITLE
Should output all assets

### ISSUE THREAD

**Issue by heygrady** [webdeveric/webpack-assets-manifest#49]
Was trying to use this in an ejected create-react-app.

1. create-react-app uses [`webpack-manifest-plugin`](https://www.npmjs.com/package/webpack-manifest-plugin), which is pretty useless (https://github.com/facebook/create-react-app/issues/5513).
2. The good thing about `webpack-manifest-plugin` is that it outputs _every_ resource, including images and resources from [`copy-webpack-plugin`](https://www.npmjs.com/package/copy-webpack-plugin)
3. The bad thing about `webpack-manifest-plugin` is that it has no support for entrypoints and integrity
4. The bad thing about `webpack-assets-manifest` is that it's pretty useless to not include every resource when using SRI. For instance, how do I get the integrity of my various vendor chunks?

Why doesn't `webpack-assets-manifest` include _every_ output resource?

**Comment by webdeveric** [comment]
Probably related to #25

**Comment by fsateler** [comment]
Looks like for some reason this plugin looks at `stats.assetsByChunkName`, but CopyWebpackPlugin does not add the files there (possibly because there is no chunk to attribute the files to?), instead it adds them to `stats.assets`

**Comment by guzart** [comment]
@webdeveric anything I can help you with to release a fix for this issue? [You mentioned](https://github.com/webdeveric/webpack-assets-manifest/pull/99#issuecomment-712194801) there are other issues you need to close?
