### ISSUE TITLE
Add callback for modifying manifest entry value

### ISSUE THREAD

**Issue by niksy** [webdeveric/webpack-assets-manifest#5]
Currently, plugin returns output file name as value of manifest entry, and that is acceptable in vast majority of cases.

Would it make sense to have callback in which you could adjust that value and have access to file stats object in that callback? By default, callback will return only output file name.

Use case: you want to output additional file information such as final file size of output file which can be used to adjust final HTML output (e.g. if the file is smaller than 1KB, inline it)

---

Configuration:

```js
plugins: [
  new Manifest({
    setValue: function ( fileStats ) {
      return { fileName: fileStats.name, size: fileStats.size };
    }
  })
]
```

manifest.json

```json
{
  "foo": { "fileName":"foo.js", "size": 123456 }
}
```

**Comment by webdeveric** [comment]
@niksy I'll look into that feature.

You could probably do this yourself by implementing your own [replacer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#The_replacer_parameter). It can be a bit tricky to do what you want since it will call `replacer` recursively if you return an object. To make things easier, I'll probably add a `beforeWrite` callback where you can totally customize the data before it gets stringified.

**Comment by niksy** [comment]
`replacer` callback gets final JSON object so you don’t have access to final file stats out of the box, you need to explictly read that file with `fs` module or something similar to get stats which seems rather inconvenient (you need to take into account public path and such).

But `beforeWrite` could be useful for that case!

**Comment by webdeveric** [comment]
@niksy I have an updated version in the `dev` branch that has some ways to customize the manifest data. The [readme](https://github.com/webdeveric/webpack-assets-manifest/tree/dev#customizing-the-manifest) has the details. I think you should probably use the `moduleAsset` and `processAssets` listeners. The build stats are available on `manifest.stats` in case you need it.

To install the updated version, run `npm i webdeveric/webpack-assets-manifest#dev`.

**Comment by niksy** [comment]
@webdeveric Great! I’ve managed to get callback for every listener except `moduleAsset`. When does this event gets called?

**Comment by webdeveric** [comment]
@niksy `moduleAsset` is used if you `import`/`require` other assets in your modules.

For example, if you use `require('logo.png')` in a module, it will add `logo.png` to the manifest.

It is emitted here: https://github.com/webdeveric/webpack-assets-manifest/blob/dev/src/WebpackAssetsManifest.js#L297

**Comment by niksy** [comment]
@webdeveric Hmm, I’ve just tried with requiring simple JS file inside one of my entry points and nothing gets outputted in that callback :/

**Comment by webdeveric** [comment]
@niksy JS files get bundled. Try requiring an image with the [file-loader](https://github.com/webpack/file-loader).

**Comment by niksy** [comment]
@webdeveric Ah, got it :+1:

**Comment by niksy** [comment]
@webdeveric Everything from here looks fine for me :+1:
