### ISSUE TITLE
Will this help prevent 404's when deploying new chunks?

### ISSUE THREAD

**Issue by williamabbott** [webdeveric/webpack-assets-manifest#50]
Vue SPA, vue router. Quick question before I take it for a spin:

Scenario: A user is active on the web app. We make a deployment. Old chunks are removed and replaced with new ones. Because SPA, rarely it's refreshed. Will this plugin help resolve this issue? 

I suppose I will have to make sure the manifest is reloaded with every route change so we can know if any asset paths have changed.

**Comment by webdeveric** [comment]
@williamabbott This plugin only records the webpack build output and its up to you to invalidate your SPA cache. Are you using [Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API#Download_install_and_activate)?

**Comment by williamabbott** [comment]
@webdeveric No I am not.

**Comment by webdeveric** [comment]
@williamabbott How are you building this SPA? Are you using hashed output filenames and the [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) to generate your `index.html` file? If so, you _might_ not need this plugin. It won't hurt anything to keep using it though. I usually add it to all my projects for auditing purposes (recording build time, CDN URLs, SRI hashes, etc.).

**Comment by williamabbott** [comment]
@webdeveric no it's a vue cli project

**Comment by webdeveric** [comment]
@williamabbott I've never used that one. Google/Stackoverflow may be your best bet for now.
Feel free to post a new issue if you run into a problem or have a feature request.
