### ISSUE TITLE
Manifest.json for each config when in multi-compiler mode

### ISSUE THREAD

**Issue by rkumorek** [webdeveric/webpack-assets-manifest#52]
Hey,
Is it possible to generate manifest.json for each config when using multi-compiler mode? Currently it only writes one to output path from last config but I need manifest for each separately.

```
const examples = ['example1', example2'];

module.exports = examples.map(example => ({
		entry: `/some/path/to/${example}/index.js`,
		output: {
                        path:  `/some/output/path/to/${example}/assets/`,
			filename: '[name].[hash].js',
                        chunkFilename: '[name].[hash].js'
		},
		plugins: [
                        new WebpackAssetsManifest()
		]
	}));
```

In each `assets` folder I'd like to have manifest.json generated.

**Comment by webdeveric** [comment]
@rkumorek Can you add `done()` like in the following example:

```js
new WebpackAssetsManifest({
  done(manifest) {
    console.log(manifest.getOutputPath());
  }
})
```

I ran your example locally with ☝️ and I got two different output paths.

You could also use an absolute path in the [`output` option](https://github.com/webdeveric/webpack-assets-manifest#output).

```js
new WebpackAssetsManifest({
  output: `/some/output/path/to/${example}/assets/manifest.json`,
})
```

**Comment by rkumorek** [comment]
Great, this works:
```
new WebpackAssetsManifest({
  output: `/some/output/path/to/${example}/assets/manifest.json`,
})
```

I think I tried that but without `/manifest.json` at the end and that's why it didn't work.

Thank you!!!
