### ISSUE TITLE
Concurrent builds and the merge option

### ISSUE THREAD

**Issue by justin808** [webdeveric/webpack-assets-manifest#64]
## The problem
Regarding using the merge option, when I run two concurrent instances of webpack to build both a client and server bundles (React server-side-rendering), and both webpack configs use the merge option, one of the updates is not used. For example, the client config reads the old server bundle hash in the manifest and, since it runs longer, it outputs the old server bundle hash even though a new server bundle was generated.

## Questions
Should this plugin support or not support concurrent access when using merge? 

If concurrent access should be supported, I'd suggest that just before writing the new values, a lock file is created, the old manifest is read, merged, and written to. For example, this could help: https://www.npmjs.com/package/proper-lockfile.

Or should this plugin explicitly not support concurrent builds and instead recommend that the webpack multi-compiler technique be used? https://github.com/webpack/webpack/tree/master/examples/multi-compiler

**Comment by justin808** [comment]
@webdeveric Any comment here? Can you confirm that the webpack multi-compiler technique is OK to ensure that concurrent webpack builds work?

I know for certain that running concurrent `webpack --watch` processes causes the "merged" manifest to be written out when the process started building, rather than reading the contents right before writing. That results in super confusing behavior of having old SHAs on the file names.

**Comment by justin808** [comment]
Merging happens:

https://github.com/webdeveric/webpack-assets-manifest/blob/master/src/WebpackAssetsManifest.js#L386-L404

Writing the file happens:

https://github.com/webdeveric/webpack-assets-manifest/blob/master/src/WebpackAssetsManifest.js#L520

Ideally, we'd lock the manifest on disk to merge, read the file, merge changes, rewrite the file, and release the lock.

Right now, we 

```
t1 ==> we read the file
t2 ==> another process saves the updates
t3 ==> we write the file, overwriting any changes by t2 
```

**Comment by justin808** [comment]
@webdeveric Any chance that you can comment on this one?

**Comment by webdeveric** [comment]
@justin808 If you use one webpack process with multiple configs, the multi-compiler example should work for you.
If you use [parallel-webpack](https://github.com/trivago/parallel-webpack), which uses separate processes, it wont.

I'm updating this plugin to use a lockfile. Its a work in progress but you can follow along in my `dev` branch.
