### ISSUE TITLE
fileExtRegex option getting ignored

### ISSUE THREAD

**Issue by mojtabaahn** [webdeveric/webpack-assets-manifest#77]
## The problem
I'm trying to filter only js and css files for manifest.json. tried a very simple regex for it and it had no effect on outputs (svg and font files did NOT get filter).

**webpack.config.js**
```js
plugins: [
    new WebpackAssetsManifest({
       fileExtRegex : /\.(?:js|css)$/i
     }),
    // ...
]
```

**manifest.json** bot after and before using fileExtRegex option:
```json
{
  "dashboard.css": "dashboard.css?id=fbceae78623b99842f53",
  "dashboard.js": "dashboard.js?id=04656c8749db88adc571",
  "main.css": "main.css?id=9b4d79776789b945fc23",
  "main.js": "main.js?id=fdcfe8bbd438c2849ef5",
  "resources/frontend/main/assets/images/authentication-modal-poster.svg": "resources/frontend/main/assets/images/authentication-modal-poster.svg?id=a83ce8a95874d8dda6854a9c8d112366",
  "resources/frontend/main/assets/images/authorization-modal-poster.svg": "resources/frontend/main/assets/images/authorization-modal-poster.svg?id=571b2807ca409f2ff264fefc317ff903",
  "vendor.js": "vendor.js?id=6a87bd1c82dd41fe5177"
}
```

### Webpack version
v4.44

### Operating system
Windows 10

**Comment by webdeveric** [comment]
The `fileExtRegex` option does not do any filtering.

You'll need to use `customize`.

Example: https://github.com/webdeveric/webpack-assets-manifest/blob/master/examples/customized.js

**Comment by mojtabaahn** [comment]
I already used **transform** hook to solve this, Do you think i need to switch to **customize** hook?

```js
new WebpackAssetsManifest({
    transform(assets, manifest) {
        let filtered = {}
        Object.entries(assets)
            .filter(([key, value]) => key.match(/\.(js|css)$/i))
            .forEach(([key, value]) => filtered[key] = value)
        return filtered
    }
})
```

Another thing i want to mention is I believe **fileExtRegex** is missleading and its usage can be explained in documentation with more details.

Thanks!

**Comment by webdeveric** [comment]
I find `customize` easier to use, especially when I want to do something based on one entry and not the entire manifest.

This should work for your use case.

```js
new WebpackAssetsManifest({
  customize(entry, original, manifest, asset) {
    const pattern = /\.(js|css)$/i;

    if ( ! pattern.test( entry.key ) ) {
      return false;
    }
  },
});
```

---

The [documentation for `fileExtRegex`](https://github.com/webdeveric/webpack-assets-manifest#fileextregex) says

> This is the regular expression used to find file extensions. You'll probably never need to change this.

I think its fairly understandable, but if you'd like to provide more detail, PRs are welcome.
