### ISSUE TITLE
Extension for entry point key

### ISSUE THREAD

**Issue by niksy** [webdeveric/webpack-assets-manifest#8]
Would it make sense to omit extension if manifest entry is Webpack entry point? It seems to me that this is maybe unecessary and can create confusion where mental model is "if I set this as Webpack entry point key, I would expect it to be the same key in manifest.json". This can also be confusing if entry point is e.g. camelcased and it’s source is snake cased (e.g. `indexEntry: 'src/index_entry.js'`)

For every other asset (imported images, extracted CSS, etc.) extension makes sense.

**Comment by webdeveric** [comment]
@niksy I think it would be confusing to omit the file extension only for `.js` files.

If you really want to do it that way, you can hook into `processAssets` and call `get()`, `set()`, and `delete()` yourself.

Also, to your point about camelCase and snake_case, you have control over the webpack config to set the entry point names. Use whatever naming style makes sense for you.

```js
module.exports = {
  entry: {
    home: './home',
    sub_page: './sub_page',
    otherSubPage: './otherSubPage',
    "yet-another-page": './yet-another-page'
  }
};
```

**Comment by niksy** [comment]
@webdeveric You’re right, but it seems like a convoluted process.

* Hook into `processAssets` and set new key/value pair
* Delete entries with `.js` extensions relying on string concatenation which can get confusing and is prone to changes

Process is similar to this, don’t know if there’s easier way for this:

```js
Object.keys(assets).forEach(( key ) => {
	manifest.set(key, assets[key]);
	manifest.delete(`${key}${manifest.getExtension(assets[key])}`);
})
```

Can this be extended to have this adjusted through configuration option? Maybe `omitEntryPointKeyExtension`?

**Comment by webdeveric** [comment]
@niksy This plugin was intended to only be a mapping from input file to output file.

How are you using the manifest file?

What is your use case for dropping the `.js` extension?

**Comment by niksy** [comment]
@webdeveric I’ve reviewed my consideration and actually think that it’s benefical to have `.js` extension for key name (I’ve tested some cases with different key names). If there is need to remove it, it can be done with `processAssets` callback. Sorry for the confusion. My reasoning comes from the simple use cases, but for complex ones like including CSS and images it can create inconsistent output values.

> How are you using the manifest file?

Currently I’m working on PHP project which consumes manifest.json and uses entry values as `src` attribute values for script tags.

> What is your use case for dropping the .js extension?

Mainly the "mental model case": if I set entry point to `index1: "index1.js"` I would expect it to be `"index1": "index1-output.js"` in manifest.json. But as I said, adding `.js` extension can be beneficial and if there is need to remove it, it can be done with callbacks.
