### ISSUE TITLE
Manifest written to wrong path in dev mode

### ISSUE THREAD

**Issue by gzaripov** [webdeveric/webpack-assets-manifest#81]
I have output: `/nginx/main/bff-manifest.json`, in dev mode because of this line 
https://github.com/webdeveric/webpack-assets-manifest/blob/9647a1175e50c83bc539463e44d6fb3c7bc1050d/src/WebpackAssetsManifest.js#L483
it is stripped to `bff-manifest.json`.

What's purpose of this `path.basename`, can we just emit it the same way as in production?

**Comment by webdeveric** [comment]
@gzaripov That only gets used if you're using `webpack-dev-server`. If I'm remembering correctly, I only keep the basename due to the dev server using a `MemoryFileSystem` which doesn't place files with an absolute path where you'd think.
