### ISSUE TITLE
Manifest is easily written twice

### ISSUE THREAD

**Issue by justin808** [webdeveric/webpack-assets-manifest#89]
## The problem
The manifest will be written twice for non-webpack-dev-server mode. This creates additional possibilities for race conditions when the handleAfterEmit is called. Suppose that between the time webpack is writing the file, per the normal way it does and the handleAfterEmit does, the manifest.json had updated. The updates would be lost.

The writing per the options.writeToDisk happens here:

https://github.com/webdeveric/webpack-assets-manifest/blob/master/src/WebpackAssetsManifest.js#L519

[rails/webpacker](https://github.com/rails/webpacker/blob/fcb57638c68ce3ecb9e343725b611ea3b12ca33b/package/environments/base.js#L47) sets this to always be true, so the default for all Rails apps is doing this, even when not running the webpack-dev-server.

```js
  result.append(
    'Manifest',
    new WebpackAssetsManifest({
      entrypoints: true,
      writeToDisk: true,
      publicPath: config.publicPathWithoutCDN
    })
  )
```

### Webpack version
4.x

### Webpack config
defaults for rails apps

## Suggestion

`writeToDisk` should be ignored if webpack is already writing the file to the disk. If the webpack-dev-server is the only case for writing the files, then we can check `process.env.WEBPACK_DEV_SERVER`.

Another option could be to always ready, merge, and write the file in the handleAfterEmit.

The advantage of that is that concurrent webpack processes would less likely overwrite each other's updates to the manifest.json.

However, I'm not sure would be for not setting the manifest here in handleEmit.

https://github.com/webdeveric/webpack-assets-manifest/blob/master/src/WebpackAssetsManifest.js#L482
```js
    compilation.assets[ output ] = new RawSource(this.toString());
```

**Comment by justin808** [comment]
@webdeveric Any chance that you can comment on this one?

**Comment by webdeveric** [comment]
@justin808 I'm working on updates for Webpack 5 at the moment. I'll try to get to this soon.

Thanks for pointing out `process.env.WEBPACK_DEV_SERVER`.That wasn't set the last time I looked for a way to detect if you're runnng `webpack-dev-server`.
