### ISSUE TITLE
How to generate multiple manifest.json files for separate parts of the PWA?

### ISSUE THREAD

**Issue by nmummau** [webdeveric/webpack-assets-manifest#97]
## The Question
[Similar to this stackoverflow question](https://stackoverflow.com/questions/46203661/possible-to-have-multiple-manifest-json-for-pwa).

Is this possible to configure? 
I would like a separate manifest.json for separate parts of my PWA, depending on which page the user is visiting.

**Comment by webdeveric** [comment]
@nmummau  Are you referring to a [web app manifests](https://developer.mozilla.org/en-US/docs/Web/Manifest)?
This plugin does not generate those.

**Comment by webdeveric** [comment]
Closing due to no response.
